name: Flutter Analyze

on: pull_request  # Run for pull request

jobs:
  review-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Write permission is required to add comments on a PR
    steps:
      - name: Clone repository
        uses: actions/checkout@v4 # Checkout code from repository
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Download & setup flutter - latest

      - name: Get Packages
        run: flutter pub get
        
      - name: Review Code
        run: flutter analyze --write=flutter_analyze.log # Run flutter analyze with --write option

      - if: ${{ !cancelled() }}               # Required to run this step even if failure
        name: Post Review Comments 
        uses: yorifuji/flutter-analyze-commenter@v1
        with:
          analyze-log: flutter_analyze.log    # file path for analyze log
          verbose: false                       # verbose output (optional)
          
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Write permission is required to add comments on a PR
    steps:
      - name: Clone repository
        uses: actions/checkout@v4 # Checkout code from repository
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Download & setup flutter - latest

      - name: Get Packages
        run: flutter pub get
        
      - if: ${{ success() }}               # Required to run this step if not failure
        name: Build Android
        run: flutter build apk --release

  build-ios:
    runs-on: macos-latest
    permissions:
      contents: read
      pull-requests: write # Write permission is required to add comments on a PR
    steps:
      - name: Clone repository
        uses: actions/checkout@v4 # Checkout code from repository
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Download & setup flutter - latest

      - name: Get Packages
        run: flutter pub get

      - if: ${{ success() }}               # Required to run this step if not failure
        name: Build iOS
        run: flutter build ios --release --no-codesign
